// Copyright (c) 2025 Samuel Calmday. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by godel-refreshable-plugin: do not edit.

package config

import (
	httpclient "github.com/palantir/conjure-go-runtime/v2/conjure-go-client/httpclient"
	refreshable "github.com/palantir/pkg/refreshable"
	wlog "github.com/palantir/witchcraft-go-logging/wlog"
	config "github.com/palantir/witchcraft-go-server/v2/config"
)

type RefreshableRuntimeConfig interface {
	refreshable.Refreshable
	CurrentRuntimeConfig() RuntimeConfig
	MapRuntimeConfig(func(RuntimeConfig) interface{}) refreshable.Refreshable
	SubscribeToRuntimeConfig(func(RuntimeConfig)) (unsubscribe func())

	Runtime() RefreshableRuntime
	MyFavoriteNumber() refreshable.Int64
}

type RefreshingRuntimeConfig struct {
	refreshable.Refreshable
}

func NewRefreshingRuntimeConfig(in refreshable.Refreshable) RefreshingRuntimeConfig {
	return RefreshingRuntimeConfig{Refreshable: in}
}

func (r RefreshingRuntimeConfig) CurrentRuntimeConfig() RuntimeConfig {
	return r.Current().(RuntimeConfig)
}

func (r RefreshingRuntimeConfig) MapRuntimeConfig(mapFn func(RuntimeConfig) interface{}) refreshable.Refreshable {
	return r.Map(func(i interface{}) interface{} {
		return mapFn(i.(RuntimeConfig))
	})
}

func (r RefreshingRuntimeConfig) SubscribeToRuntimeConfig(consumer func(RuntimeConfig)) (unsubscribe func()) {
	return r.Subscribe(func(i interface{}) {
		consumer(i.(RuntimeConfig))
	})
}

func (r RefreshingRuntimeConfig) Runtime() RefreshableRuntime {
	return NewRefreshingRuntime(r.MapRuntimeConfig(func(i RuntimeConfig) interface{} {
		return i.Runtime
	}))
}

func (r RefreshingRuntimeConfig) MyFavoriteNumber() refreshable.Int64 {
	return refreshable.NewInt64(r.MapRuntimeConfig(func(i RuntimeConfig) interface{} {
		return i.MyFavoriteNumber
	}))
}

type RefreshableRuntime interface {
	refreshable.Refreshable
	CurrentRuntime() config.Runtime
	MapRuntime(func(config.Runtime) interface{}) refreshable.Refreshable
	SubscribeToRuntime(func(config.Runtime)) (unsubscribe func())

	DiagnosticsConfig() RefreshableDiagnosticsConfig
	HealthChecks() RefreshableHealthChecksConfig
	AuditConfig() RefreshableAuditConfigPtr
	LoggerConfig() RefreshableLoggerConfigPtr
	ServiceDiscovery() RefreshableServicesConfig
}

type RefreshingRuntime struct {
	refreshable.Refreshable
}

func NewRefreshingRuntime(in refreshable.Refreshable) RefreshingRuntime {
	return RefreshingRuntime{Refreshable: in}
}

func (r RefreshingRuntime) CurrentRuntime() config.Runtime {
	return r.Current().(config.Runtime)
}

func (r RefreshingRuntime) MapRuntime(mapFn func(config.Runtime) interface{}) refreshable.Refreshable {
	return r.Map(func(i interface{}) interface{} {
		return mapFn(i.(config.Runtime))
	})
}

func (r RefreshingRuntime) SubscribeToRuntime(consumer func(config.Runtime)) (unsubscribe func()) {
	return r.Subscribe(func(i interface{}) {
		consumer(i.(config.Runtime))
	})
}

func (r RefreshingRuntime) DiagnosticsConfig() RefreshableDiagnosticsConfig {
	return NewRefreshingDiagnosticsConfig(r.MapRuntime(func(i config.Runtime) interface{} {
		return i.DiagnosticsConfig
	}))
}

func (r RefreshingRuntime) HealthChecks() RefreshableHealthChecksConfig {
	return NewRefreshingHealthChecksConfig(r.MapRuntime(func(i config.Runtime) interface{} {
		return i.HealthChecks
	}))
}

func (r RefreshingRuntime) AuditConfig() RefreshableAuditConfigPtr {
	return NewRefreshingAuditConfigPtr(r.MapRuntime(func(i config.Runtime) interface{} {
		return i.AuditConfig
	}))
}

func (r RefreshingRuntime) LoggerConfig() RefreshableLoggerConfigPtr {
	return NewRefreshingLoggerConfigPtr(r.MapRuntime(func(i config.Runtime) interface{} {
		return i.LoggerConfig
	}))
}

func (r RefreshingRuntime) ServiceDiscovery() RefreshableServicesConfig {
	return NewRefreshingServicesConfig(r.MapRuntime(func(i config.Runtime) interface{} {
		return i.ServiceDiscovery
	}))
}

type RefreshableDiagnosticsConfig interface {
	refreshable.Refreshable
	CurrentDiagnosticsConfig() config.DiagnosticsConfig
	MapDiagnosticsConfig(func(config.DiagnosticsConfig) interface{}) refreshable.Refreshable
	SubscribeToDiagnosticsConfig(func(config.DiagnosticsConfig)) (unsubscribe func())

	DebugSharedSecret() refreshable.String
	DebugSharedSecretFile() refreshable.String
}

type RefreshingDiagnosticsConfig struct {
	refreshable.Refreshable
}

func NewRefreshingDiagnosticsConfig(in refreshable.Refreshable) RefreshingDiagnosticsConfig {
	return RefreshingDiagnosticsConfig{Refreshable: in}
}

func (r RefreshingDiagnosticsConfig) CurrentDiagnosticsConfig() config.DiagnosticsConfig {
	return r.Current().(config.DiagnosticsConfig)
}

func (r RefreshingDiagnosticsConfig) MapDiagnosticsConfig(mapFn func(config.DiagnosticsConfig) interface{}) refreshable.Refreshable {
	return r.Map(func(i interface{}) interface{} {
		return mapFn(i.(config.DiagnosticsConfig))
	})
}

func (r RefreshingDiagnosticsConfig) SubscribeToDiagnosticsConfig(consumer func(config.DiagnosticsConfig)) (unsubscribe func()) {
	return r.Subscribe(func(i interface{}) {
		consumer(i.(config.DiagnosticsConfig))
	})
}

func (r RefreshingDiagnosticsConfig) DebugSharedSecret() refreshable.String {
	return refreshable.NewString(r.MapDiagnosticsConfig(func(i config.DiagnosticsConfig) interface{} {
		return i.DebugSharedSecret
	}))
}

func (r RefreshingDiagnosticsConfig) DebugSharedSecretFile() refreshable.String {
	return refreshable.NewString(r.MapDiagnosticsConfig(func(i config.DiagnosticsConfig) interface{} {
		return i.DebugSharedSecretFile
	}))
}

type RefreshableHealthChecksConfig interface {
	refreshable.Refreshable
	CurrentHealthChecksConfig() config.HealthChecksConfig
	MapHealthChecksConfig(func(config.HealthChecksConfig) interface{}) refreshable.Refreshable
	SubscribeToHealthChecksConfig(func(config.HealthChecksConfig)) (unsubscribe func())

	SharedSecret() refreshable.String
}

type RefreshingHealthChecksConfig struct {
	refreshable.Refreshable
}

func NewRefreshingHealthChecksConfig(in refreshable.Refreshable) RefreshingHealthChecksConfig {
	return RefreshingHealthChecksConfig{Refreshable: in}
}

func (r RefreshingHealthChecksConfig) CurrentHealthChecksConfig() config.HealthChecksConfig {
	return r.Current().(config.HealthChecksConfig)
}

func (r RefreshingHealthChecksConfig) MapHealthChecksConfig(mapFn func(config.HealthChecksConfig) interface{}) refreshable.Refreshable {
	return r.Map(func(i interface{}) interface{} {
		return mapFn(i.(config.HealthChecksConfig))
	})
}

func (r RefreshingHealthChecksConfig) SubscribeToHealthChecksConfig(consumer func(config.HealthChecksConfig)) (unsubscribe func()) {
	return r.Subscribe(func(i interface{}) {
		consumer(i.(config.HealthChecksConfig))
	})
}

func (r RefreshingHealthChecksConfig) SharedSecret() refreshable.String {
	return refreshable.NewString(r.MapHealthChecksConfig(func(i config.HealthChecksConfig) interface{} {
		return i.SharedSecret
	}))
}

type RefreshableAuditConfigPtr interface {
	refreshable.Refreshable
	CurrentAuditConfigPtr() *config.AuditConfig
	MapAuditConfigPtr(func(*config.AuditConfig) interface{}) refreshable.Refreshable
	SubscribeToAuditConfigPtr(func(*config.AuditConfig)) (unsubscribe func())

	Deployment() refreshable.String
	Product() refreshable.String
	ProductVersion() refreshable.String
	Stack() refreshable.String
	Service() refreshable.String
	Environment() refreshable.String
}

type RefreshingAuditConfigPtr struct {
	refreshable.Refreshable
}

func NewRefreshingAuditConfigPtr(in refreshable.Refreshable) RefreshingAuditConfigPtr {
	return RefreshingAuditConfigPtr{Refreshable: in}
}

func (r RefreshingAuditConfigPtr) CurrentAuditConfigPtr() *config.AuditConfig {
	return r.Current().(*config.AuditConfig)
}

func (r RefreshingAuditConfigPtr) MapAuditConfigPtr(mapFn func(*config.AuditConfig) interface{}) refreshable.Refreshable {
	return r.Map(func(i interface{}) interface{} {
		return mapFn(i.(*config.AuditConfig))
	})
}

func (r RefreshingAuditConfigPtr) SubscribeToAuditConfigPtr(consumer func(*config.AuditConfig)) (unsubscribe func()) {
	return r.Subscribe(func(i interface{}) {
		consumer(i.(*config.AuditConfig))
	})
}

func (r RefreshingAuditConfigPtr) Deployment() refreshable.String {
	return refreshable.NewString(r.MapAuditConfigPtr(func(i *config.AuditConfig) interface{} {
		return i.Deployment
	}))
}

func (r RefreshingAuditConfigPtr) Product() refreshable.String {
	return refreshable.NewString(r.MapAuditConfigPtr(func(i *config.AuditConfig) interface{} {
		return i.Product
	}))
}

func (r RefreshingAuditConfigPtr) ProductVersion() refreshable.String {
	return refreshable.NewString(r.MapAuditConfigPtr(func(i *config.AuditConfig) interface{} {
		return i.ProductVersion
	}))
}

func (r RefreshingAuditConfigPtr) Stack() refreshable.String {
	return refreshable.NewString(r.MapAuditConfigPtr(func(i *config.AuditConfig) interface{} {
		return i.Stack
	}))
}

func (r RefreshingAuditConfigPtr) Service() refreshable.String {
	return refreshable.NewString(r.MapAuditConfigPtr(func(i *config.AuditConfig) interface{} {
		return i.Service
	}))
}

func (r RefreshingAuditConfigPtr) Environment() refreshable.String {
	return refreshable.NewString(r.MapAuditConfigPtr(func(i *config.AuditConfig) interface{} {
		return i.Environment
	}))
}

type RefreshableAuditConfig interface {
	refreshable.Refreshable
	CurrentAuditConfig() config.AuditConfig
	MapAuditConfig(func(config.AuditConfig) interface{}) refreshable.Refreshable
	SubscribeToAuditConfig(func(config.AuditConfig)) (unsubscribe func())

	Deployment() refreshable.String
	Product() refreshable.String
	ProductVersion() refreshable.String
	Stack() refreshable.String
	Service() refreshable.String
	Environment() refreshable.String
}

type RefreshingAuditConfig struct {
	refreshable.Refreshable
}

func NewRefreshingAuditConfig(in refreshable.Refreshable) RefreshingAuditConfig {
	return RefreshingAuditConfig{Refreshable: in}
}

func (r RefreshingAuditConfig) CurrentAuditConfig() config.AuditConfig {
	return r.Current().(config.AuditConfig)
}

func (r RefreshingAuditConfig) MapAuditConfig(mapFn func(config.AuditConfig) interface{}) refreshable.Refreshable {
	return r.Map(func(i interface{}) interface{} {
		return mapFn(i.(config.AuditConfig))
	})
}

func (r RefreshingAuditConfig) SubscribeToAuditConfig(consumer func(config.AuditConfig)) (unsubscribe func()) {
	return r.Subscribe(func(i interface{}) {
		consumer(i.(config.AuditConfig))
	})
}

func (r RefreshingAuditConfig) Deployment() refreshable.String {
	return refreshable.NewString(r.MapAuditConfig(func(i config.AuditConfig) interface{} {
		return i.Deployment
	}))
}

func (r RefreshingAuditConfig) Product() refreshable.String {
	return refreshable.NewString(r.MapAuditConfig(func(i config.AuditConfig) interface{} {
		return i.Product
	}))
}

func (r RefreshingAuditConfig) ProductVersion() refreshable.String {
	return refreshable.NewString(r.MapAuditConfig(func(i config.AuditConfig) interface{} {
		return i.ProductVersion
	}))
}

func (r RefreshingAuditConfig) Stack() refreshable.String {
	return refreshable.NewString(r.MapAuditConfig(func(i config.AuditConfig) interface{} {
		return i.Stack
	}))
}

func (r RefreshingAuditConfig) Service() refreshable.String {
	return refreshable.NewString(r.MapAuditConfig(func(i config.AuditConfig) interface{} {
		return i.Service
	}))
}

func (r RefreshingAuditConfig) Environment() refreshable.String {
	return refreshable.NewString(r.MapAuditConfig(func(i config.AuditConfig) interface{} {
		return i.Environment
	}))
}

type RefreshableLoggerConfigPtr interface {
	refreshable.Refreshable
	CurrentLoggerConfigPtr() *config.LoggerConfig
	MapLoggerConfigPtr(func(*config.LoggerConfig) interface{}) refreshable.Refreshable
	SubscribeToLoggerConfigPtr(func(*config.LoggerConfig)) (unsubscribe func())

	Level() RefreshableLogLevel
}

type RefreshingLoggerConfigPtr struct {
	refreshable.Refreshable
}

func NewRefreshingLoggerConfigPtr(in refreshable.Refreshable) RefreshingLoggerConfigPtr {
	return RefreshingLoggerConfigPtr{Refreshable: in}
}

func (r RefreshingLoggerConfigPtr) CurrentLoggerConfigPtr() *config.LoggerConfig {
	return r.Current().(*config.LoggerConfig)
}

func (r RefreshingLoggerConfigPtr) MapLoggerConfigPtr(mapFn func(*config.LoggerConfig) interface{}) refreshable.Refreshable {
	return r.Map(func(i interface{}) interface{} {
		return mapFn(i.(*config.LoggerConfig))
	})
}

func (r RefreshingLoggerConfigPtr) SubscribeToLoggerConfigPtr(consumer func(*config.LoggerConfig)) (unsubscribe func()) {
	return r.Subscribe(func(i interface{}) {
		consumer(i.(*config.LoggerConfig))
	})
}

func (r RefreshingLoggerConfigPtr) Level() RefreshableLogLevel {
	return NewRefreshingLogLevel(r.MapLoggerConfigPtr(func(i *config.LoggerConfig) interface{} {
		return i.Level
	}))
}

type RefreshableLoggerConfig interface {
	refreshable.Refreshable
	CurrentLoggerConfig() config.LoggerConfig
	MapLoggerConfig(func(config.LoggerConfig) interface{}) refreshable.Refreshable
	SubscribeToLoggerConfig(func(config.LoggerConfig)) (unsubscribe func())

	Level() RefreshableLogLevel
}

type RefreshingLoggerConfig struct {
	refreshable.Refreshable
}

func NewRefreshingLoggerConfig(in refreshable.Refreshable) RefreshingLoggerConfig {
	return RefreshingLoggerConfig{Refreshable: in}
}

func (r RefreshingLoggerConfig) CurrentLoggerConfig() config.LoggerConfig {
	return r.Current().(config.LoggerConfig)
}

func (r RefreshingLoggerConfig) MapLoggerConfig(mapFn func(config.LoggerConfig) interface{}) refreshable.Refreshable {
	return r.Map(func(i interface{}) interface{} {
		return mapFn(i.(config.LoggerConfig))
	})
}

func (r RefreshingLoggerConfig) SubscribeToLoggerConfig(consumer func(config.LoggerConfig)) (unsubscribe func()) {
	return r.Subscribe(func(i interface{}) {
		consumer(i.(config.LoggerConfig))
	})
}

func (r RefreshingLoggerConfig) Level() RefreshableLogLevel {
	return NewRefreshingLogLevel(r.MapLoggerConfig(func(i config.LoggerConfig) interface{} {
		return i.Level
	}))
}

type RefreshableLogLevel interface {
	refreshable.Refreshable
	CurrentLogLevel() wlog.LogLevel
	MapLogLevel(func(wlog.LogLevel) interface{}) refreshable.Refreshable
	SubscribeToLogLevel(func(wlog.LogLevel)) (unsubscribe func())
}

type RefreshingLogLevel struct {
	refreshable.Refreshable
}

func NewRefreshingLogLevel(in refreshable.Refreshable) RefreshingLogLevel {
	return RefreshingLogLevel{Refreshable: in}
}

func (r RefreshingLogLevel) CurrentLogLevel() wlog.LogLevel {
	return r.Current().(wlog.LogLevel)
}

func (r RefreshingLogLevel) MapLogLevel(mapFn func(wlog.LogLevel) interface{}) refreshable.Refreshable {
	return r.Map(func(i interface{}) interface{} {
		return mapFn(i.(wlog.LogLevel))
	})
}

func (r RefreshingLogLevel) SubscribeToLogLevel(consumer func(wlog.LogLevel)) (unsubscribe func()) {
	return r.Subscribe(func(i interface{}) {
		consumer(i.(wlog.LogLevel))
	})
}

type RefreshableServicesConfig interface {
	refreshable.Refreshable
	CurrentServicesConfig() httpclient.ServicesConfig
	MapServicesConfig(func(httpclient.ServicesConfig) interface{}) refreshable.Refreshable
	SubscribeToServicesConfig(func(httpclient.ServicesConfig)) (unsubscribe func())

	Default() RefreshableClientConfig
	Services() RefreshableStringToClientConfig
}

type RefreshingServicesConfig struct {
	refreshable.Refreshable
}

func NewRefreshingServicesConfig(in refreshable.Refreshable) RefreshingServicesConfig {
	return RefreshingServicesConfig{Refreshable: in}
}

func (r RefreshingServicesConfig) CurrentServicesConfig() httpclient.ServicesConfig {
	return r.Current().(httpclient.ServicesConfig)
}

func (r RefreshingServicesConfig) MapServicesConfig(mapFn func(httpclient.ServicesConfig) interface{}) refreshable.Refreshable {
	return r.Map(func(i interface{}) interface{} {
		return mapFn(i.(httpclient.ServicesConfig))
	})
}

func (r RefreshingServicesConfig) SubscribeToServicesConfig(consumer func(httpclient.ServicesConfig)) (unsubscribe func()) {
	return r.Subscribe(func(i interface{}) {
		consumer(i.(httpclient.ServicesConfig))
	})
}

func (r RefreshingServicesConfig) Default() RefreshableClientConfig {
	return NewRefreshingClientConfig(r.MapServicesConfig(func(i httpclient.ServicesConfig) interface{} {
		return i.Default
	}))
}

func (r RefreshingServicesConfig) Services() RefreshableStringToClientConfig {
	return NewRefreshingStringToClientConfig(r.MapServicesConfig(func(i httpclient.ServicesConfig) interface{} {
		return i.Services
	}))
}

type RefreshableClientConfig interface {
	refreshable.Refreshable
	CurrentClientConfig() httpclient.ClientConfig
	MapClientConfig(func(httpclient.ClientConfig) interface{}) refreshable.Refreshable
	SubscribeToClientConfig(func(httpclient.ClientConfig)) (unsubscribe func())

	ServiceName() refreshable.String
	URIs() refreshable.StringSlice
	APIToken() refreshable.StringPtr
	APITokenFile() refreshable.StringPtr
	BasicAuth() RefreshableBasicAuthPtr
	DisableHTTP2() refreshable.BoolPtr
	ProxyFromEnvironment() refreshable.BoolPtr
	ProxyURL() refreshable.StringPtr
	MaxNumRetries() refreshable.IntPtr
	InitialBackoff() refreshable.DurationPtr
	MaxBackoff() refreshable.DurationPtr
	ConnectTimeout() refreshable.DurationPtr
	ReadTimeout() refreshable.DurationPtr
	WriteTimeout() refreshable.DurationPtr
	IdleConnTimeout() refreshable.DurationPtr
	TLSHandshakeTimeout() refreshable.DurationPtr
	ExpectContinueTimeout() refreshable.DurationPtr
	ResponseHeaderTimeout() refreshable.DurationPtr
	KeepAlive() refreshable.DurationPtr
	HTTP2ReadIdleTimeout() refreshable.DurationPtr
	HTTP2PingTimeout() refreshable.DurationPtr
	MaxIdleConns() refreshable.IntPtr
	MaxIdleConnsPerHost() refreshable.IntPtr
	Metrics() RefreshableMetricsConfig
	Security() RefreshableSecurityConfig
}

type RefreshingClientConfig struct {
	refreshable.Refreshable
}

func NewRefreshingClientConfig(in refreshable.Refreshable) RefreshingClientConfig {
	return RefreshingClientConfig{Refreshable: in}
}

func (r RefreshingClientConfig) CurrentClientConfig() httpclient.ClientConfig {
	return r.Current().(httpclient.ClientConfig)
}

func (r RefreshingClientConfig) MapClientConfig(mapFn func(httpclient.ClientConfig) interface{}) refreshable.Refreshable {
	return r.Map(func(i interface{}) interface{} {
		return mapFn(i.(httpclient.ClientConfig))
	})
}

func (r RefreshingClientConfig) SubscribeToClientConfig(consumer func(httpclient.ClientConfig)) (unsubscribe func()) {
	return r.Subscribe(func(i interface{}) {
		consumer(i.(httpclient.ClientConfig))
	})
}

func (r RefreshingClientConfig) ServiceName() refreshable.String {
	return refreshable.NewString(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.ServiceName
	}))
}

func (r RefreshingClientConfig) URIs() refreshable.StringSlice {
	return refreshable.NewStringSlice(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.URIs
	}))
}

func (r RefreshingClientConfig) APIToken() refreshable.StringPtr {
	return refreshable.NewStringPtr(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.APIToken
	}))
}

func (r RefreshingClientConfig) APITokenFile() refreshable.StringPtr {
	return refreshable.NewStringPtr(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.APITokenFile
	}))
}

func (r RefreshingClientConfig) BasicAuth() RefreshableBasicAuthPtr {
	return NewRefreshingBasicAuthPtr(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.BasicAuth
	}))
}

func (r RefreshingClientConfig) DisableHTTP2() refreshable.BoolPtr {
	return refreshable.NewBoolPtr(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.DisableHTTP2
	}))
}

func (r RefreshingClientConfig) ProxyFromEnvironment() refreshable.BoolPtr {
	return refreshable.NewBoolPtr(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.ProxyFromEnvironment
	}))
}

func (r RefreshingClientConfig) ProxyURL() refreshable.StringPtr {
	return refreshable.NewStringPtr(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.ProxyURL
	}))
}

func (r RefreshingClientConfig) MaxNumRetries() refreshable.IntPtr {
	return refreshable.NewIntPtr(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.MaxNumRetries
	}))
}

func (r RefreshingClientConfig) InitialBackoff() refreshable.DurationPtr {
	return refreshable.NewDurationPtr(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.InitialBackoff
	}))
}

func (r RefreshingClientConfig) MaxBackoff() refreshable.DurationPtr {
	return refreshable.NewDurationPtr(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.MaxBackoff
	}))
}

func (r RefreshingClientConfig) ConnectTimeout() refreshable.DurationPtr {
	return refreshable.NewDurationPtr(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.ConnectTimeout
	}))
}

func (r RefreshingClientConfig) ReadTimeout() refreshable.DurationPtr {
	return refreshable.NewDurationPtr(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.ReadTimeout
	}))
}

func (r RefreshingClientConfig) WriteTimeout() refreshable.DurationPtr {
	return refreshable.NewDurationPtr(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.WriteTimeout
	}))
}

func (r RefreshingClientConfig) IdleConnTimeout() refreshable.DurationPtr {
	return refreshable.NewDurationPtr(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.IdleConnTimeout
	}))
}

func (r RefreshingClientConfig) TLSHandshakeTimeout() refreshable.DurationPtr {
	return refreshable.NewDurationPtr(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.TLSHandshakeTimeout
	}))
}

func (r RefreshingClientConfig) ExpectContinueTimeout() refreshable.DurationPtr {
	return refreshable.NewDurationPtr(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.ExpectContinueTimeout
	}))
}

func (r RefreshingClientConfig) ResponseHeaderTimeout() refreshable.DurationPtr {
	return refreshable.NewDurationPtr(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.ResponseHeaderTimeout
	}))
}

func (r RefreshingClientConfig) KeepAlive() refreshable.DurationPtr {
	return refreshable.NewDurationPtr(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.KeepAlive
	}))
}

func (r RefreshingClientConfig) HTTP2ReadIdleTimeout() refreshable.DurationPtr {
	return refreshable.NewDurationPtr(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.HTTP2ReadIdleTimeout
	}))
}

func (r RefreshingClientConfig) HTTP2PingTimeout() refreshable.DurationPtr {
	return refreshable.NewDurationPtr(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.HTTP2PingTimeout
	}))
}

func (r RefreshingClientConfig) MaxIdleConns() refreshable.IntPtr {
	return refreshable.NewIntPtr(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.MaxIdleConns
	}))
}

func (r RefreshingClientConfig) MaxIdleConnsPerHost() refreshable.IntPtr {
	return refreshable.NewIntPtr(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.MaxIdleConnsPerHost
	}))
}

func (r RefreshingClientConfig) Metrics() RefreshableMetricsConfig {
	return NewRefreshingMetricsConfig(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.Metrics
	}))
}

func (r RefreshingClientConfig) Security() RefreshableSecurityConfig {
	return NewRefreshingSecurityConfig(r.MapClientConfig(func(i httpclient.ClientConfig) interface{} {
		return i.Security
	}))
}

type RefreshableBasicAuthPtr interface {
	refreshable.Refreshable
	CurrentBasicAuthPtr() *httpclient.BasicAuth
	MapBasicAuthPtr(func(*httpclient.BasicAuth) interface{}) refreshable.Refreshable
	SubscribeToBasicAuthPtr(func(*httpclient.BasicAuth)) (unsubscribe func())

	User() refreshable.String
	Password() refreshable.String
}

type RefreshingBasicAuthPtr struct {
	refreshable.Refreshable
}

func NewRefreshingBasicAuthPtr(in refreshable.Refreshable) RefreshingBasicAuthPtr {
	return RefreshingBasicAuthPtr{Refreshable: in}
}

func (r RefreshingBasicAuthPtr) CurrentBasicAuthPtr() *httpclient.BasicAuth {
	return r.Current().(*httpclient.BasicAuth)
}

func (r RefreshingBasicAuthPtr) MapBasicAuthPtr(mapFn func(*httpclient.BasicAuth) interface{}) refreshable.Refreshable {
	return r.Map(func(i interface{}) interface{} {
		return mapFn(i.(*httpclient.BasicAuth))
	})
}

func (r RefreshingBasicAuthPtr) SubscribeToBasicAuthPtr(consumer func(*httpclient.BasicAuth)) (unsubscribe func()) {
	return r.Subscribe(func(i interface{}) {
		consumer(i.(*httpclient.BasicAuth))
	})
}

func (r RefreshingBasicAuthPtr) User() refreshable.String {
	return refreshable.NewString(r.MapBasicAuthPtr(func(i *httpclient.BasicAuth) interface{} {
		return i.User
	}))
}

func (r RefreshingBasicAuthPtr) Password() refreshable.String {
	return refreshable.NewString(r.MapBasicAuthPtr(func(i *httpclient.BasicAuth) interface{} {
		return i.Password
	}))
}

type RefreshableBasicAuth interface {
	refreshable.Refreshable
	CurrentBasicAuth() httpclient.BasicAuth
	MapBasicAuth(func(httpclient.BasicAuth) interface{}) refreshable.Refreshable
	SubscribeToBasicAuth(func(httpclient.BasicAuth)) (unsubscribe func())

	User() refreshable.String
	Password() refreshable.String
}

type RefreshingBasicAuth struct {
	refreshable.Refreshable
}

func NewRefreshingBasicAuth(in refreshable.Refreshable) RefreshingBasicAuth {
	return RefreshingBasicAuth{Refreshable: in}
}

func (r RefreshingBasicAuth) CurrentBasicAuth() httpclient.BasicAuth {
	return r.Current().(httpclient.BasicAuth)
}

func (r RefreshingBasicAuth) MapBasicAuth(mapFn func(httpclient.BasicAuth) interface{}) refreshable.Refreshable {
	return r.Map(func(i interface{}) interface{} {
		return mapFn(i.(httpclient.BasicAuth))
	})
}

func (r RefreshingBasicAuth) SubscribeToBasicAuth(consumer func(httpclient.BasicAuth)) (unsubscribe func()) {
	return r.Subscribe(func(i interface{}) {
		consumer(i.(httpclient.BasicAuth))
	})
}

func (r RefreshingBasicAuth) User() refreshable.String {
	return refreshable.NewString(r.MapBasicAuth(func(i httpclient.BasicAuth) interface{} {
		return i.User
	}))
}

func (r RefreshingBasicAuth) Password() refreshable.String {
	return refreshable.NewString(r.MapBasicAuth(func(i httpclient.BasicAuth) interface{} {
		return i.Password
	}))
}

type RefreshableMetricsConfig interface {
	refreshable.Refreshable
	CurrentMetricsConfig() httpclient.MetricsConfig
	MapMetricsConfig(func(httpclient.MetricsConfig) interface{}) refreshable.Refreshable
	SubscribeToMetricsConfig(func(httpclient.MetricsConfig)) (unsubscribe func())

	Enabled() refreshable.BoolPtr
	Tags() RefreshableStringToString
}

type RefreshingMetricsConfig struct {
	refreshable.Refreshable
}

func NewRefreshingMetricsConfig(in refreshable.Refreshable) RefreshingMetricsConfig {
	return RefreshingMetricsConfig{Refreshable: in}
}

func (r RefreshingMetricsConfig) CurrentMetricsConfig() httpclient.MetricsConfig {
	return r.Current().(httpclient.MetricsConfig)
}

func (r RefreshingMetricsConfig) MapMetricsConfig(mapFn func(httpclient.MetricsConfig) interface{}) refreshable.Refreshable {
	return r.Map(func(i interface{}) interface{} {
		return mapFn(i.(httpclient.MetricsConfig))
	})
}

func (r RefreshingMetricsConfig) SubscribeToMetricsConfig(consumer func(httpclient.MetricsConfig)) (unsubscribe func()) {
	return r.Subscribe(func(i interface{}) {
		consumer(i.(httpclient.MetricsConfig))
	})
}

func (r RefreshingMetricsConfig) Enabled() refreshable.BoolPtr {
	return refreshable.NewBoolPtr(r.MapMetricsConfig(func(i httpclient.MetricsConfig) interface{} {
		return i.Enabled
	}))
}

func (r RefreshingMetricsConfig) Tags() RefreshableStringToString {
	return NewRefreshingStringToString(r.MapMetricsConfig(func(i httpclient.MetricsConfig) interface{} {
		return i.Tags
	}))
}

type RefreshableStringToString interface {
	refreshable.Refreshable
	CurrentStringToString() map[string]string
	MapStringToString(func(map[string]string) interface{}) refreshable.Refreshable
	SubscribeToStringToString(func(map[string]string)) (unsubscribe func())
}

type RefreshingStringToString struct {
	refreshable.Refreshable
}

func NewRefreshingStringToString(in refreshable.Refreshable) RefreshingStringToString {
	return RefreshingStringToString{Refreshable: in}
}

func (r RefreshingStringToString) CurrentStringToString() map[string]string {
	return r.Current().(map[string]string)
}

func (r RefreshingStringToString) MapStringToString(mapFn func(map[string]string) interface{}) refreshable.Refreshable {
	return r.Map(func(i interface{}) interface{} {
		return mapFn(i.(map[string]string))
	})
}

func (r RefreshingStringToString) SubscribeToStringToString(consumer func(map[string]string)) (unsubscribe func()) {
	return r.Subscribe(func(i interface{}) {
		consumer(i.(map[string]string))
	})
}

type RefreshableSecurityConfig interface {
	refreshable.Refreshable
	CurrentSecurityConfig() httpclient.SecurityConfig
	MapSecurityConfig(func(httpclient.SecurityConfig) interface{}) refreshable.Refreshable
	SubscribeToSecurityConfig(func(httpclient.SecurityConfig)) (unsubscribe func())

	CAFiles() refreshable.StringSlice
	CertFile() refreshable.String
	KeyFile() refreshable.String
	InsecureSkipVerify() refreshable.BoolPtr
}

type RefreshingSecurityConfig struct {
	refreshable.Refreshable
}

func NewRefreshingSecurityConfig(in refreshable.Refreshable) RefreshingSecurityConfig {
	return RefreshingSecurityConfig{Refreshable: in}
}

func (r RefreshingSecurityConfig) CurrentSecurityConfig() httpclient.SecurityConfig {
	return r.Current().(httpclient.SecurityConfig)
}

func (r RefreshingSecurityConfig) MapSecurityConfig(mapFn func(httpclient.SecurityConfig) interface{}) refreshable.Refreshable {
	return r.Map(func(i interface{}) interface{} {
		return mapFn(i.(httpclient.SecurityConfig))
	})
}

func (r RefreshingSecurityConfig) SubscribeToSecurityConfig(consumer func(httpclient.SecurityConfig)) (unsubscribe func()) {
	return r.Subscribe(func(i interface{}) {
		consumer(i.(httpclient.SecurityConfig))
	})
}

func (r RefreshingSecurityConfig) CAFiles() refreshable.StringSlice {
	return refreshable.NewStringSlice(r.MapSecurityConfig(func(i httpclient.SecurityConfig) interface{} {
		return i.CAFiles
	}))
}

func (r RefreshingSecurityConfig) CertFile() refreshable.String {
	return refreshable.NewString(r.MapSecurityConfig(func(i httpclient.SecurityConfig) interface{} {
		return i.CertFile
	}))
}

func (r RefreshingSecurityConfig) KeyFile() refreshable.String {
	return refreshable.NewString(r.MapSecurityConfig(func(i httpclient.SecurityConfig) interface{} {
		return i.KeyFile
	}))
}

func (r RefreshingSecurityConfig) InsecureSkipVerify() refreshable.BoolPtr {
	return refreshable.NewBoolPtr(r.MapSecurityConfig(func(i httpclient.SecurityConfig) interface{} {
		return i.InsecureSkipVerify
	}))
}

type RefreshableStringToClientConfig interface {
	refreshable.Refreshable
	CurrentStringToClientConfig() map[string]httpclient.ClientConfig
	MapStringToClientConfig(func(map[string]httpclient.ClientConfig) interface{}) refreshable.Refreshable
	SubscribeToStringToClientConfig(func(map[string]httpclient.ClientConfig)) (unsubscribe func())
}

type RefreshingStringToClientConfig struct {
	refreshable.Refreshable
}

func NewRefreshingStringToClientConfig(in refreshable.Refreshable) RefreshingStringToClientConfig {
	return RefreshingStringToClientConfig{Refreshable: in}
}

func (r RefreshingStringToClientConfig) CurrentStringToClientConfig() map[string]httpclient.ClientConfig {
	return r.Current().(map[string]httpclient.ClientConfig)
}

func (r RefreshingStringToClientConfig) MapStringToClientConfig(mapFn func(map[string]httpclient.ClientConfig) interface{}) refreshable.Refreshable {
	return r.Map(func(i interface{}) interface{} {
		return mapFn(i.(map[string]httpclient.ClientConfig))
	})
}

func (r RefreshingStringToClientConfig) SubscribeToStringToClientConfig(consumer func(map[string]httpclient.ClientConfig)) (unsubscribe func()) {
	return r.Subscribe(func(i interface{}) {
		consumer(i.(map[string]httpclient.ClientConfig))
	})
}

type RefreshableInstallConfig interface {
	refreshable.Refreshable
	CurrentInstallConfig() InstallConfig
	MapInstallConfig(func(InstallConfig) interface{}) refreshable.Refreshable
	SubscribeToInstallConfig(func(InstallConfig)) (unsubscribe func())

	Install() RefreshableInstall
	MyNumber() refreshable.Int
	Database() RefreshableDatabaseConfig
}

type RefreshingInstallConfig struct {
	refreshable.Refreshable
}

func NewRefreshingInstallConfig(in refreshable.Refreshable) RefreshingInstallConfig {
	return RefreshingInstallConfig{Refreshable: in}
}

func (r RefreshingInstallConfig) CurrentInstallConfig() InstallConfig {
	return r.Current().(InstallConfig)
}

func (r RefreshingInstallConfig) MapInstallConfig(mapFn func(InstallConfig) interface{}) refreshable.Refreshable {
	return r.Map(func(i interface{}) interface{} {
		return mapFn(i.(InstallConfig))
	})
}

func (r RefreshingInstallConfig) SubscribeToInstallConfig(consumer func(InstallConfig)) (unsubscribe func()) {
	return r.Subscribe(func(i interface{}) {
		consumer(i.(InstallConfig))
	})
}

func (r RefreshingInstallConfig) Install() RefreshableInstall {
	return NewRefreshingInstall(r.MapInstallConfig(func(i InstallConfig) interface{} {
		return i.Install
	}))
}

func (r RefreshingInstallConfig) MyNumber() refreshable.Int {
	return refreshable.NewInt(r.MapInstallConfig(func(i InstallConfig) interface{} {
		return i.MyNumber
	}))
}

func (r RefreshingInstallConfig) Database() RefreshableDatabaseConfig {
	return NewRefreshingDatabaseConfig(r.MapInstallConfig(func(i InstallConfig) interface{} {
		return i.Database
	}))
}

type RefreshableInstall interface {
	refreshable.Refreshable
	CurrentInstall() config.Install
	MapInstall(func(config.Install) interface{}) refreshable.Refreshable
	SubscribeToInstall(func(config.Install)) (unsubscribe func())

	ProductName() refreshable.String
	ProductVersion() refreshable.String
	Server() RefreshableServer
	MetricsEmitFrequency() refreshable.Duration
	TraceSampleRate() refreshable.Float64Ptr
	ManagementTraceSampleRate() refreshable.Float64Ptr
	UseConsoleLog() refreshable.Bool
	UseWrappedLogs() refreshable.Bool
}

type RefreshingInstall struct {
	refreshable.Refreshable
}

func NewRefreshingInstall(in refreshable.Refreshable) RefreshingInstall {
	return RefreshingInstall{Refreshable: in}
}

func (r RefreshingInstall) CurrentInstall() config.Install {
	return r.Current().(config.Install)
}

func (r RefreshingInstall) MapInstall(mapFn func(config.Install) interface{}) refreshable.Refreshable {
	return r.Map(func(i interface{}) interface{} {
		return mapFn(i.(config.Install))
	})
}

func (r RefreshingInstall) SubscribeToInstall(consumer func(config.Install)) (unsubscribe func()) {
	return r.Subscribe(func(i interface{}) {
		consumer(i.(config.Install))
	})
}

func (r RefreshingInstall) ProductName() refreshable.String {
	return refreshable.NewString(r.MapInstall(func(i config.Install) interface{} {
		return i.ProductName
	}))
}

func (r RefreshingInstall) ProductVersion() refreshable.String {
	return refreshable.NewString(r.MapInstall(func(i config.Install) interface{} {
		return i.ProductVersion
	}))
}

func (r RefreshingInstall) Server() RefreshableServer {
	return NewRefreshingServer(r.MapInstall(func(i config.Install) interface{} {
		return i.Server
	}))
}

func (r RefreshingInstall) MetricsEmitFrequency() refreshable.Duration {
	return refreshable.NewDuration(r.MapInstall(func(i config.Install) interface{} {
		return i.MetricsEmitFrequency
	}))
}

func (r RefreshingInstall) TraceSampleRate() refreshable.Float64Ptr {
	return refreshable.NewFloat64Ptr(r.MapInstall(func(i config.Install) interface{} {
		return i.TraceSampleRate
	}))
}

func (r RefreshingInstall) ManagementTraceSampleRate() refreshable.Float64Ptr {
	return refreshable.NewFloat64Ptr(r.MapInstall(func(i config.Install) interface{} {
		return i.ManagementTraceSampleRate
	}))
}

func (r RefreshingInstall) UseConsoleLog() refreshable.Bool {
	return refreshable.NewBool(r.MapInstall(func(i config.Install) interface{} {
		return i.UseConsoleLog
	}))
}

func (r RefreshingInstall) UseWrappedLogs() refreshable.Bool {
	return refreshable.NewBool(r.MapInstall(func(i config.Install) interface{} {
		return i.UseWrappedLogs
	}))
}

type RefreshableServer interface {
	refreshable.Refreshable
	CurrentServer() config.Server
	MapServer(func(config.Server) interface{}) refreshable.Refreshable
	SubscribeToServer(func(config.Server)) (unsubscribe func())

	Address() refreshable.String
	Port() refreshable.Int
	ManagementPort() refreshable.Int
	ContextPath() refreshable.String
	ClientCAFiles() refreshable.StringSlice
	CertFile() refreshable.String
	KeyFile() refreshable.String
}

type RefreshingServer struct {
	refreshable.Refreshable
}

func NewRefreshingServer(in refreshable.Refreshable) RefreshingServer {
	return RefreshingServer{Refreshable: in}
}

func (r RefreshingServer) CurrentServer() config.Server {
	return r.Current().(config.Server)
}

func (r RefreshingServer) MapServer(mapFn func(config.Server) interface{}) refreshable.Refreshable {
	return r.Map(func(i interface{}) interface{} {
		return mapFn(i.(config.Server))
	})
}

func (r RefreshingServer) SubscribeToServer(consumer func(config.Server)) (unsubscribe func()) {
	return r.Subscribe(func(i interface{}) {
		consumer(i.(config.Server))
	})
}

func (r RefreshingServer) Address() refreshable.String {
	return refreshable.NewString(r.MapServer(func(i config.Server) interface{} {
		return i.Address
	}))
}

func (r RefreshingServer) Port() refreshable.Int {
	return refreshable.NewInt(r.MapServer(func(i config.Server) interface{} {
		return i.Port
	}))
}

func (r RefreshingServer) ManagementPort() refreshable.Int {
	return refreshable.NewInt(r.MapServer(func(i config.Server) interface{} {
		return i.ManagementPort
	}))
}

func (r RefreshingServer) ContextPath() refreshable.String {
	return refreshable.NewString(r.MapServer(func(i config.Server) interface{} {
		return i.ContextPath
	}))
}

func (r RefreshingServer) ClientCAFiles() refreshable.StringSlice {
	return refreshable.NewStringSlice(r.MapServer(func(i config.Server) interface{} {
		return i.ClientCAFiles
	}))
}

func (r RefreshingServer) CertFile() refreshable.String {
	return refreshable.NewString(r.MapServer(func(i config.Server) interface{} {
		return i.CertFile
	}))
}

func (r RefreshingServer) KeyFile() refreshable.String {
	return refreshable.NewString(r.MapServer(func(i config.Server) interface{} {
		return i.KeyFile
	}))
}

type RefreshableDatabaseConfig interface {
	refreshable.Refreshable
	CurrentDatabaseConfig() DatabaseConfig
	MapDatabaseConfig(func(DatabaseConfig) interface{}) refreshable.Refreshable
	SubscribeToDatabaseConfig(func(DatabaseConfig)) (unsubscribe func())

	Type() refreshable.String
	ConnectionString() refreshable.String
}

type RefreshingDatabaseConfig struct {
	refreshable.Refreshable
}

func NewRefreshingDatabaseConfig(in refreshable.Refreshable) RefreshingDatabaseConfig {
	return RefreshingDatabaseConfig{Refreshable: in}
}

func (r RefreshingDatabaseConfig) CurrentDatabaseConfig() DatabaseConfig {
	return r.Current().(DatabaseConfig)
}

func (r RefreshingDatabaseConfig) MapDatabaseConfig(mapFn func(DatabaseConfig) interface{}) refreshable.Refreshable {
	return r.Map(func(i interface{}) interface{} {
		return mapFn(i.(DatabaseConfig))
	})
}

func (r RefreshingDatabaseConfig) SubscribeToDatabaseConfig(consumer func(DatabaseConfig)) (unsubscribe func()) {
	return r.Subscribe(func(i interface{}) {
		consumer(i.(DatabaseConfig))
	})
}

func (r RefreshingDatabaseConfig) Type() refreshable.String {
	return refreshable.NewString(r.MapDatabaseConfig(func(i DatabaseConfig) interface{} {
		return i.Type
	}))
}

func (r RefreshingDatabaseConfig) ConnectionString() refreshable.String {
	return refreshable.NewString(r.MapDatabaseConfig(func(i DatabaseConfig) interface{} {
		return i.ConnectionString
	}))
}
